create table tpg01_forma_pago (id_forma_pago int4 not null, id_cliente int4 not null, id_tipo int4 not null, id_estado int4 not null, st_visible int4 not null, primary key (id_forma_pago));
create table tpg02_tipo_forma (id_tipo int4 not null, nb_tipo varchar(50) not null, primary key (id_tipo));
create table tpg03_paypal (id_forma_pago int4 not null, nb_usuario varchar(64) not null, tx_contrasena varchar(64) not null, primary key (id_forma_pago));
create table tpg04_tarjeta (id_forma_pago int4 not null, id_tipo int4 not null, tx_nu_tarjeta varchar(24) not null, fh_exp_date time(7) not null, tx_cvv varchar(3) not null, primary key (id_forma_pago));
create table tpg05_tipo_tarjeta (id_tipo int4 not null, nb_tipo varchar(50) not null, primary key (id_tipo));
create table tpg06_efectivo (id_forma_pago int4 not null, primary key (id_forma_pago));
create table tpd07_cola_espera (id_cola int4 not null, id_local int4 not null, fh_cola date not null, tm_ultima_act time(7) not null, primary key (id_cola));
create table tpd08_tipo_orden (id_tipo int4 not null, nb_tipo varchar(50) not null, primary key (id_tipo));
create table tau01_cuenta (id_cuenta int4 not null, id_estado int4 not null, nb_usuario varchar(50) not null unique, tx_correo varchar(50) not null, tx_contrasena varchar(64) not null, fh_creacion date not null, primary key (id_cuenta));
create table tpd06_orden_producto (id_orden int4 not null, id_local int4 not null, id_articulo int4 not null, tx_comentaro varchar(50), nu_rating numeric(2,1) not null, nu_cantidad int4 not null, primary key (id_orden, id_local, id_articulo));
create table tau10_acceso (id_acceso int4 not null, fh_ultimo_acceso timestamp(0), nu_intentos int4, st_sesion_activa int4 not null, primary key (id_acceso));
create table tau09_persona (id_persona int4 not null, nb_persona varchar(50) not null, tx_primer_ap varchar(50) not null, tx_segundo_ap varchar(50), by_foto bytea, primary key (id_persona));
create table tpd01_cliente (id_cliente int4 not null, id_persona int4, primary key (id_cliente));
create table tpd02_orden (id_orden int4 not null, id_cliente int4 not null, id_estado int4 not null, id_cola int4, id_forma_pago int4 not null, id_tipo int4 not null, fh_dia timestamp(0) not null, fh_ultima_act timestamp(0) not null, st_prioridad int4, st_confirmacion bool not null, primary key (id_orden));
create table tpd03_estado_orden (id_estado int4 not null, nb_estado varchar(50) not null, primary key (id_estado));
create table tpd04_orden_atencion (id_orden int4 not null, id_empleado int4 not null, id_estado int4 not null, primary key (id_orden));
create table tpd05_estado_orden_atencion (id_estado  serial not null, nb_estado varchar(50) not null, primary key (id_estado));
create table tau03_rol (id_rol int4 not null, nb_rol varchar(50) not null, ds_rol varchar(100) not null, primary key (id_rol));
create table tps12_cafeteria (id_cafeteria int4 not null, id_dueno int4 not null, nb_cafeteria varchar(50) not null, primary key (id_cafeteria));
create table tps04_dueno (id_dueno int4 not null, primary key (id_dueno));
create table tps07_paquete (id_paquete int4 not null, primary key (id_paquete));
create table tps05_producto (id_producto int4 not null, id_tipo int4 not null, id_estado int4 not null, id_cafeteria int4 not null, nb_producto varchar(50) not null, tm_estimado_prep numeric(3, 1), nu_rating int4 not null, tx_descripcion varchar(150) not null, by_foto bytea, primary key (id_producto));
create table tau02_estado_cuenta (id_estado int4 not null, nb_estado varchar(50), primary key (id_estado));
create table tps09_estado_local (id_estado int4 not null, nb_estado varchar(50) not null, primary key (id_estado));
create table tps10_estado_producto (id_estado int4 not null, nb_estado varchar(50) not null, primary key (id_estado));
create table tau04_rol_cuenta (id_rol int4 not null, id_cuenta int4 not null, primary key (id_rol, id_cuenta));
create table tau08_recurso (id_recurso int4 not null, nb_recurso varchar(50) not null, tx_uri varchar(50) not null, primary key (id_recurso));
create table tau05_metodo (id_metodo int4 not null, nb_metodo varchar(50) not null, primary key (id_metodo));
create table tau06_metodo_recurso (id_metodo int4 not null, id_recurso int4 not null, primary key (id_metodo, id_recurso));
create table tau07_rol_recurso (id_rol int4 not null, id_metodo int4 not null, id_recurso int4 not null, primary key (id_rol, id_metodo, id_recurso));
create table tps02_empleado (id_empleado int4 not null, id_local int4 not null, st_responsable int4 not null, primary key (id_empleado));
create table tps01_local (id_local int4 not null, id_estado int4 not null, id_cafeteria int4 not null, nb_local varchar(50) not null, nu_rating numeric(2, 1) not null, nu_longitud numeric(9, 6) not null, nu_latitud numeric(9, 6) not null, tm_inicio timestamp(0) not null, tm_fin timestamp(0) not null, by_foto bytea, tx_direccion varchar(200) not null, primary key (id_local));
create table tps06_tipo_producto (id_tipo int4 not null, nb_tipo varchar(50), primary key (id_tipo));
create table tps09_producto_local (id_local int4 not null, id_producto int4 not null, id_estado int4 not null, nu_precio_venta numeric(6, 2), primary key (id_local, id_producto));
create table tps10_paquete_producto (id_paquete int4 not null, id_local int4 not null, id_producto int4 not null, st_aplica_prom int4 not null, primary key (id_paquete, id_local, id_producto));
create table tps11_disponibilidad (id_disponibilidad int4 not null, id_local int4 not null, id_producto int4 not null, tm_fecha_ini timestamp(0) not null, nu_existencia_ini int4 not null, nu_existencia_ac int4 not null, tm_fecha_ag int4, primary key (id_disponibilidad));
create table tps12_estado_producto_local (id_estado  serial not null, nb_estado varchar(50) not null, primary key (id_estado));
create table tpg07_estado_forma_pago (id_estado int4 not null, nb_estado varchar(50) not null, primary key (id_estado));
create table tps13_promocion (id_promocion int4 not null, id_local int4 not null, nb_promocion varchar(50) not null, tx_descripcion varchar(100) not null, nu_precio numeric(6, 2) not null, fecha_inicio timestamp(0) not null, fh_fin timestamp(0), nu_porcentaje numeric(3, 0) not null, primary key (id_promocion));
create table tps14_producto_promocion (id_promocion int4 not null, id_local int4 not null, id_producto int4 not null, nu_precio_final numeric(6, 2), primary key (id_promocion, id_local, id_producto));
alter table tau04_rol_cuenta add constraint FKtau04_rol_810558 foreign key (id_rol) references tau03_rol;
alter table tau04_rol_cuenta add constraint FKtau04_rol_898427 foreign key (id_cuenta) references tau01_cuenta;
alter table tau01_cuenta add constraint FKtau01_cuen190525 foreign key (id_estado) references tau02_estado_cuenta;
alter table tau06_metodo_recurso add constraint FKtau06_meto210420 foreign key (id_metodo) references tau05_metodo;
alter table tau06_metodo_recurso add constraint FKtau06_meto438935 foreign key (id_recurso) references tau08_recurso;
alter table tau07_rol_recurso add constraint FKtau07_rol_903539 foreign key (id_rol) references tau03_rol;
alter table tau07_rol_recurso add constraint FKtau07_rol_296738 foreign key (id_metodo, id_recurso) references tau06_metodo_recurso;
alter table tau01_cuenta add constraint FKtau01_cuen351505 foreign key (id_cuenta) references tau09_persona;
alter table tau10_acceso add constraint FKtau10_acce453872 foreign key (id_acceso) references tau01_cuenta;
alter table tps05_producto add constraint FKtps05_prod885617 foreign key (id_estado) references tps10_estado_producto;
alter table tps05_producto add constraint FKtps05_prod413324 foreign key (id_tipo) references tps06_tipo_producto;
alter table tps04_dueno add constraint FKtps04_duen913262 foreign key (id_dueno) references tau09_persona;
alter table tps02_empleado add constraint FKtps02_empl59562 foreign key (id_empleado) references tau09_persona;
alter table tps01_local add constraint FKtps01_loca523937 foreign key (id_estado) references tps09_estado_local;
alter table tps02_empleado add constraint FKtps02_empl518823 foreign key (id_local) references tps01_local;
alter table tpd02_orden add constraint FKtpd02_orde681330 foreign key (id_cliente) references tpd01_cliente;
alter table tpd01_cliente add constraint FKtpd01_clie572336 foreign key (id_persona) references tau09_persona;
alter table tpd02_orden add constraint FKtpd02_orde822482 foreign key (id_estado) references tpd03_estado_orden;
alter table tpd04_orden_atencion add constraint FKtpd04_orde138334 foreign key (id_orden) references tpd02_orden;
alter table tpd04_orden_atencion add constraint FKtpd04_orde48625 foreign key (id_estado) references tpd05_estado_orden_atencion;
alter table tpd04_orden_atencion add constraint FKtpd04_orde895378 foreign key (id_empleado) references tps02_empleado;
alter table tps12_cafeteria add constraint FKtps12_cafe919106 foreign key (id_dueno) references tps04_dueno;
alter table tps01_local add constraint FKtps01_loca633803 foreign key (id_cafeteria) references tps12_cafeteria;
alter table tpg01_forma_pago add constraint FKtpg01_form860153 foreign key (id_cliente) references tpd01_cliente;
alter table tpg01_forma_pago add constraint FKtpg01_form806168 foreign key (id_tipo) references tpg02_tipo_forma;
alter table tpg03_paypal add constraint FKtpg03_payp105084 foreign key (id_forma_pago) references tpg01_forma_pago;
alter table tpg04_tarjeta add constraint FKtpg04_tarj329796 foreign key (id_forma_pago) references tpg01_forma_pago;
alter table tpg04_tarjeta add constraint FKtpg04_tarj233264 foreign key (id_tipo) references tpg05_tipo_tarjeta;
alter table tpd06_orden_producto add constraint FKtpd06_orde693571 foreign key (id_orden) references tpd02_orden;
alter table tpd06_orden_producto add constraint FKtpd06_orde114898 foreign key (id_local, id_articulo) references tps09_producto_local;
alter table tpg06_efectivo add constraint FKtpg06_efec890503 foreign key (id_forma_pago) references tpg01_forma_pago;
alter table tpd02_orden add constraint FKtpd02_orde875343 foreign key (id_forma_pago) references tpg01_forma_pago;
alter table tpd02_orden add constraint FKtpd02_orde227652 foreign key (id_cola) references tpd07_cola_espera;
alter table tpd07_cola_espera add constraint FKtpd07_cola892813 foreign key (id_local) references tps01_local;
alter table tpd02_orden add constraint FKtpd02_orde826545 foreign key (id_tipo) references tpd08_tipo_orden;
alter table tps07_paquete add constraint FKtps07_paqu115096 foreign key (id_paquete) references tps05_producto;
alter table tps05_producto add constraint FKtps05_prod229724 foreign key (id_cafeteria) references tps12_cafeteria;
alter table tps09_producto_local add constraint FKtps09_prod505986 foreign key (id_local) references tps01_local;
alter table tps09_producto_local add constraint FKtps09_prod545201 foreign key (id_producto) references tps05_producto;
alter table tps10_paquete_producto add constraint FKtps10_paqu114146 foreign key (id_paquete) references tps07_paquete;
alter table tps10_paquete_producto add constraint FKtps10_paqu113678 foreign key (id_local, id_producto) references tps09_producto_local;
alter table tps11_disponibilidad add constraint FKtps11_disp34902 foreign key (id_local, id_producto) references tps09_producto_local;
alter table tps09_producto_local add constraint FKtps09_prod314099 foreign key (id_estado) references tps12_estado_producto_local;
alter table tpg01_forma_pago add constraint FKtpg01_form27937 foreign key (id_estado) references tpg07_estado_forma_pago;
alter table tps14_producto_promocion add constraint FKtps14_prod203743 foreign key (id_promocion) references tps13_promocion;
alter table tps14_producto_promocion add constraint FKtps14_prod873470 foreign key (id_local, id_producto) references tps09_producto_local;
alter table tps13_promocion add constraint FKtps13_prom893085 foreign key (id_local) references tps01_local;
create sequence tpd01_cliente_seq owned by tpd01_cliente.id_cliente;
create sequence tpd02_orden_sequence owned by tpd02_orden.id_orden;
create sequence tps11_disponibilidad_seq owned by tps11_disponibilidad.id_disponibilidad;
create sequence tps13_promocion_seq owned by tps13_promocion.id_promocion;
create sequence tpg01_forma_pago_seq owned by tpg01_forma_pago.id_forma_pago;
create sequence tpd07_cola_seq owned by tpd07_cola_espera.id_cola;
create sequence tau09_persona_seq owned by tau09_persona.id_persona;
create sequence tau03_rol_seq owned by tau03_rol.id_rol;
create sequence tps12_cafeteria_seq owned by tps12_cafeteria.id_cafeteria;
create sequence tps05_producto_seq owned by tps05_producto.id_producto;
create sequence tau08_recurso_seq owned by tau08_recurso.id_recurso;
create sequence tps01_local_seq owned by tps01_local.id_local;